routes/web.php
<?php

use App\Http\Controllers\ProductsController;
use App\Http\Controllers\Admin\ProductsController as AdminProductsController;
use App\Http\Controllers\Admin\CategoriesController as AdminCategoriesController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('language')->group(function (){
    Route::get('/', [ProductsController::class,'index'])->name('dashboards');
    Route::get('products/{product}',[ProductsController::class,'show'])->name('products.show');
    Route::prefix('admin')->name('admin.')->group(function (){
        Route::resource('products' , AdminProductsController::class);
        Route::resource('categories', AdminCategoriesController::class)->except('show');
    });
    Auth::routes();
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

Route::get('language/{locale}',
    [App\Http\Controllers\LanguageSwitcherController::class, 'switcher']
)->name('language.switcher')->where('locale','en|ru');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Product extends Model implements TranslatableContract
{
    use HasFactory , Translatable;

    /**
     * @var string[]
     */
    public $translatedAttributes = ['name'];

    /**
     * @var string[]
     */
    protected $fillable = ['price' , 'picture', 'category_id' , 'description'];

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

}

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Form\ProductForm;
use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        $products = Product::orderBy('id','desc')->paginate(10);
        return view('admin.products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(ProductRequest $request): RedirectResponse
    {
        $product = ProductForm::execute($request);
        $product->save();
        return redirect()->route('admin.products.index')->with('status' , "$product->name" . " successfully created!");
    }

    /**
     * Display the specified resource.
     *
     * @param Product $product
     * @return Application|Factory|View|Response
     */
    public function show(Product $product)
    {
        return view('admin.products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Product $product
     * @return Application|Factory|View|Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('admin.products.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductRequest $request
     * @param Product $product
     * @return RedirectResponse
     */
    public function update(ProductRequest $request, Product $product): RedirectResponse
    {
        $product->update($request->all());
        $product->save();
        return redirect()->route('admin.products.index')->with('status', $product->name . ' successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Product $product
     * @return RedirectResponse
     */
    public function destroy(Product $product): RedirectResponse
    {
        $product->delete();
        return redirect()->route("admin.products.index")->with('status', ' successfully deleted!');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        $products = Product::orderBy('id','desc')->paginate(12);
        $categories = Category::all();
        return view('products.index',compact('products', 'categories'));
    }


    /**
     * Display the specified resource.
     *
     * @param Product $product
     * @return Application|Factory|View|Response
     */
    public function show(Product $product)
    {
        return view('products.show', compact('product'));
    }

}

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Добавить новый товар</h1>

    <div class="row">
        <form enctype="multipart/form-data" action="{{route('admin.products.store')}}" method="POST"> @csrf
            <div class="form-group">
                <label for="name">@lang('messages.name')</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name"/>
                @error('name')
                <p class="text-danger">{{$message}}</p>
                @enderror
            </div>
            <div class="form-group">
                <label for="price">@lang('messages.price')</label>
                <input type="number" step=".01" id="price" class="form-control @error('price') is-invalid @enderror" name="price">
                @error('price')
                <p class="text-danger">{{$message}}</p>
                @enderror
            </div>
            <div class="form-group">
                <label for="description">description</label>
                <input type="text"  id="description" class="form-control" name="description">
            </div>
            <div class="form-group">
                <select class="custom-select" name="category_id">
                    @foreach($categories as $category)
                        <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="picture">@lang('messages.picture')</label>
                <input type="file" id="picture" name="picture">
            </div>
            <br>
            <button type="submit">Добавить</button>
        </form>
    </div>

</div>

@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">
        <h1>Изменить товар</h1>
        <div class="row">
            <form enctype="multipart/form-data" action="{{route('admin.products.update' ,['product' => $product])}}" method="POST">
                @method('PUT') @csrf
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" id="name" name="name" value="{{$product->name}}"/>
                </div>
                <div class="form-group">
                    <label for="price">Цена</label>
                    <input type="number" step=".01" id="price" name="price" value="{{$product->price}}">
                </div>
                <div class="form-group">
                    <select class="custom-select" name="category_id">
                        @foreach($categories as $category)
                            <option value="{{$category->id}}">@if($category == $product->category) selected  @endif  {{$category->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="picture">Фото</label>
                    <input type="file" id="picture" name="picture" value="{{$product->picture}}">
                </div>
                <br>
                <button type="submit">Изменить</button>
            </form>
        </div>

    </div>



@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-lg container-md container-sm container-xl">
        <a href="{{route('admin.products.create')}}" class="btn btn-primary">@lang('messages.create_new_products')</a>
        <a href="{{route('admin.categories.index')}}" class="btn btn-outline-primary">all categories</a>
        <br>
        <h1>@lang('messages.products_list')</h1>
        @include('stations.status')
        <table class="table">
            <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>@lang('messages.name')</th>
                <th>@lang('messages.price')</th>
                <th>Category</th>
                <th>@lang('messages.picture')</th>
                <th>@lang('messages.action')</th>
            </tr>
            </thead>
            <tbody>
            @foreach($products as $product)
                <tr>
                    <td>{{$product->id}}</td>
                    <td><a href="{{route('admin.products.show' ,['product' => $product])}}">{{$product->name}}</a></td>
                    <td>{{$product->price}} $</td>
                    <td>@if(!is_null($product->category))
                        {{$product->category->name}}
                        @else
                            No category
                        @endif</td>
                    <td>
                        @if(!is_null($product->picture))
                            <img width="50px" height="50px" src="{{asset('/storage/' . $product->picture)}}" alt="{{$product->picture}}">
                        @else
                            <p>not picture</p>
                        @endif
                    </td>
                    <td>
                        <a href="{{route('admin.products.edit' , ['product' => $product])}}" class="btn btn-primary">@lang('messages.edit')</a>
                        <br>
                        <br>
                        <form method="POST" action="{{route('admin.products.destroy' ,['product' => $product])}}">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger">@lang('messages.delete')</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div>
            {{$products->links('pagination::bootstrap-4')}}
        </div>


    </div>


@endsection

resources/views/admin/products/show.blade.php
@extends('layouts.app')


@section('content')

    <div class="cardShow" style="width: 18rem" >
        <img src="{{asset('/storage/' .$product->picture)}}" alt="{{$product->picture}}}" class="card-img-top" alt="{{$product->picture}}">
        <div class="card-body">
            <h5 class="card-title">{{$product->name}}</h5>
            <p>Цена: {{$product->price}} $</p>
            <p>Описание:{{$product->description}}</p>
            @if(!is_null($product->category))
                <h4>Категория:{{$product->category->name}}</h4>
            @else
                <h4>No category</h4>
            @endif
            <h4><b>Comments</b></h4>
            <div class="block">
                @foreach($product->comments as $comment)
                    <h1>Author: {{$comment->author}}</h1>
                    <p>Comment: {{$comment->body}}</p>
                @endforeach
            </div>
            <a href="{{route('admin.products.index')}}" class="btn btn-primary">@lang('messages.back')</a>
        </div>
    </div>
@endsection