routes/web.php
<?php

use App\Http\Controllers\ProductsController;
use App\Http\Controllers\Admin\ProductsController as AdminProductsController;
use App\Http\Controllers\Admin\CategoriesController as AdminCategoriesController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('language')->group(function (){
    Route::get('/', [ProductsController::class,'index'])->name('dashboards');
    Route::get('products/{product}',[ProductsController::class,'show'])->name('products.show');
    Route::prefix('admin')->name('admin.')->group(function (){
        Route::resource('products' , AdminProductsController::class);
        Route::resource('categories', AdminCategoriesController::class)->except('show');
    });
    Auth::routes();
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

Route::get('language/{locale}',
    [App\Http\Controllers\LanguageSwitcherController::class, 'switcher']
)->name('language.switcher')->where('locale','en|ru');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    use HasFactory;

    /**
     * @var string[]
     */
    protected $fillable = ['name', 'description'];

    /**
     * @return HasMany
     */
    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $category = new Category();
        $category->name = $request->input('name');
        $category->save();
        return redirect()->route('admin.categories.index');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param Category $category
     * @return Application|Factory|View|Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Category $category
     * @return RedirectResponse
     */
    public function update(Request $request, Category $category): RedirectResponse
    {
        $category->update($request->all());
        $category->save();
        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return RedirectResponse
     */
    public function destroy(Category $category): RedirectResponse
    {
        $category->delete();
        return redirect()->route('admin.categories.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')


@section('content')
    <h3>Создать категорию</h3>
    <form enctype="multipart/form-data" action="{{route('admin.categories.store')}}" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Название</label>
            <input type="text" id="name" name="name">
        </div>
        <button type="submit">Создать</button>
    </form>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')


@section('content')
    <h3>Редактировать категорию</h3>
    <form enctype="multipart/form-data" action="{{route('admin.categories.update' , ['category' => $category])}}" method="POST">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="name">Название</label>
            <input type="text" id="name" name="name" value="{{$category->name}}">
        </div>
        <button type="submit">Создать</button>
    </form>


@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')


@section('content')

    <h1>Все категории</h1>
    <a href="{{route('admin.categories.create')}}" class="btn btn-primary">Добавить категорию</a>
    <a href="{{route('admin.products.index')}}"  class="btn btn-primary">Список продуктов</a>
    <br>
    <br>
    <table class="table">
        <thead class="table-dark">
        <tr>
            <th>#</th>
            <th>name</th>
            <th>action</th>
        </tr>
        </thead>
        <tbody>
       @foreach($categories as $category)
           <tr>
               <td>{{$category->id}}</td>
               <td>{{$category->name}}</td>
               <td>
                   <a href="{{route('admin.categories.edit' , ['category' => $category])}}" class="btn btn-primary">edit</a>
                   <br>
                   <br>
                   <form method="POST" action="{{route('admin.categories.destroy', ['category' => $category])}}">
                       @method('DELETE')@csrf
                       <button type="submit" class="btn btn-danger">delete</button>
                   </form>
               </td>
           </tr>
       @endforeach
        </tbody>
    </table>


@endsection